//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeViajes.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaDeViajes.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente Destino.
        /// </summary>
        internal static string ClienteDestino {
            get {
                return ResourceManager.GetString("ClienteDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente Fiscal.
        /// </summary>
        internal static string ClienteFiscal {
            get {
                return ResourceManager.GetString("ClienteFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente Origen.
        /// </summary>
        internal static string ClienteOrigen {
            get {
                return ResourceManager.GetString("ClienteOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLIENTES.
        /// </summary>
        internal static string ClientesUpper {
            get {
                return ResourceManager.GetString("ClientesUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comisión.
        /// </summary>
        internal static string Comision {
            get {
                return ResourceManager.GetString("Comision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo por Kilometro.
        /// </summary>
        internal static string CostoxKilometro {
            get {
                return ResourceManager.GetString("CostoxKilometro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CP Destino.
        /// </summary>
        internal static string CPDestino {
            get {
                return ResourceManager.GetString("CPDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CP Origen.
        /// </summary>
        internal static string CPOrigen {
            get {
                return ResourceManager.GetString("CPOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Destino.
        /// </summary>
        internal static string EstadoDestino {
            get {
                return ResourceManager.GetString("EstadoDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Origen.
        /// </summary>
        internal static string EstadoOrigen {
            get {
                return ResourceManager.GetString("EstadoOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Estatus.
        /// </summary>
        internal static string EstatusViaje {
            get {
                return ResourceManager.GetString("EstatusViaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folio.
        /// </summary>
        internal static string Folio {
            get {
                return ResourceManager.GetString("Folio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial Viaje.
        /// </summary>
        internal static string Historial_viaje {
            get {
                return ResourceManager.GetString("Historial_viaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HISTORIAL VIAJES.
        /// </summary>
        internal static string Historial_viajeUpper {
            get {
                return ResourceManager.GetString("Historial_viajeUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kilometros.
        /// </summary>
        internal static string Kilometros {
            get {
                return ResourceManager.GetString("Kilometros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Comercial.
        /// </summary>
        internal static string NombreComercial {
            get {
                return ResourceManager.GetString("NombreComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedido.
        /// </summary>
        internal static string Pedido {
            get {
                return ResourceManager.GetString("Pedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pedidos.
        /// </summary>
        internal static string Pedidos {
            get {
                return ResourceManager.GetString("Pedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PEDIDOS.
        /// </summary>
        internal static string PedidosUpper {
            get {
                return ResourceManager.GetString("PedidosUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso.
        /// </summary>
        internal static string Peso {
            get {
                return ResourceManager.GetString("Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso Máximo.
        /// </summary>
        internal static string PesoMaximo {
            get {
                return ResourceManager.GetString("PesoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso Total.
        /// </summary>
        internal static string PesoTotal {
            get {
                return ResourceManager.GetString("PesoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piezas.
        /// </summary>
        internal static string Piezas {
            get {
                return ResourceManager.GetString("Piezas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Placas.
        /// </summary>
        internal static string Placas {
            get {
                return ResourceManager.GetString("Placas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje de Venta.
        /// </summary>
        internal static string PorcentajeVenta {
            get {
                return ResourceManager.GetString("PorcentajeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón Social.
        /// </summary>
        internal static string RazonSocial {
            get {
                return ResourceManager.GetString("RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta.
        /// </summary>
        internal static string Ruta {
            get {
                return ResourceManager.GetString("Ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rutas.
        /// </summary>
        internal static string Rutas {
            get {
                return ResourceManager.GetString("Rutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUTAS.
        /// </summary>
        internal static string RutasUpper {
            get {
                return ResourceManager.GetString("RutasUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sucursal.
        /// </summary>
        internal static string Sucursal {
            get {
                return ResourceManager.GetString("Sucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sucursales.
        /// </summary>
        internal static string Sucursales {
            get {
                return ResourceManager.GetString("Sucursales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SUCURSALES.
        /// </summary>
        internal static string SucursalesUpper {
            get {
                return ResourceManager.GetString("SucursalesUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarifas.
        /// </summary>
        internal static string Tarifas {
            get {
                return ResourceManager.GetString("Tarifas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TARIFAS.
        /// </summary>
        internal static string TarifasUpper {
            get {
                return ResourceManager.GetString("TarifasUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportista.
        /// </summary>
        internal static string Transportista {
            get {
                return ResourceManager.GetString("Transportista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportistas.
        /// </summary>
        internal static string Transportistas {
            get {
                return ResourceManager.GetString("Transportistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TRANSPORTISTAS.
        /// </summary>
        internal static string TransportistasUpper {
            get {
                return ResourceManager.GetString("TransportistasUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad.
        /// </summary>
        internal static string Unidad {
            get {
                return ResourceManager.GetString("Unidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades.
        /// </summary>
        internal static string Unidades {
            get {
                return ResourceManager.GetString("Unidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UNIDADES.
        /// </summary>
        internal static string UnidadesUpper {
            get {
                return ResourceManager.GetString("UnidadesUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viajes.
        /// </summary>
        internal static string Viajes {
            get {
                return ResourceManager.GetString("Viajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VIAJES.
        /// </summary>
        internal static string ViajesUpper {
            get {
                return ResourceManager.GetString("ViajesUpper", resourceCulture);
            }
        }
    }
}
